<html>
<head>
</head>
<body>
<p><strong>Register a User Account</strong></p>
<form name="form1" method="post" action="/user/create">
  <p>First Name: 
    <input name="fName" type="text" id="fName">
  </p>
  <p>
    Last Name: 
    <input name="lName" type="text" id="lName">
  </p>
  <p>Email Address: 
    <input name="email" type="text" id="email">
  </p>
  <p>Username:
    <input name="user" type="text" id="user">
  </p>
  <p>Password: 
    <input name="pass" type="password" id="pass">
  </p>
  <p>Confirm Password: 
    <input name="passConfirm" type=\
    "password" id="passConfirm">
  </p>
  <p>
    <input name="Register" type="submit" id="Register"
 value="Register">
  </p>
</form>
</body>
</html>